version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "Europe/London"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
