version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    reviewers:
      - "spthm"
    schedule:
      interval: "daily"
      time: "18:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 1

  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - "spthm"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
