ci:
    skip: [flake8]

repos:
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
    - id: isort
      language_version: python3.9

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    - id: black
      language_version: python3.9

  # Lint after formatting.
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.2
    hooks:
    - id: flake8
      additional_dependencies:
          - pep8-naming
      language_version: python3.9
